# Generated by Django 6.0.4 on 2026-04-15 17:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker_type', models.CharField(choices=[('individual', 'Individual'), ('company_representative', 'Company representative')], max_length=30)),
                ('rfc', models.CharField(max_length=13)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('brokerage_name', models.CharField(blank=True, max_length=255)),
                ('certification_name', models.CharField(blank=True, max_length=255)),
                ('certification_number', models.CharField(blank=True, max_length=100)),
                ('company_legal_name', models.CharField(blank=True, max_length=255)),
                ('company_rfc', models.CharField(blank=True, max_length=13)),
                ('representative_job_title', models.CharField(blank=True, max_length=255)),
                ('has_authority_to_represent', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs info')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('needs_info_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_broker_declaration_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broker_profiles',
            },
        ),
    ]
