# Generated by Django 6.0.4 on 2026-04-17 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_broker_data_to_profiles(apps, schema_editor):
    BrokerProfile = apps.get_model("accounts", "BrokerProfile")
    UserProfile = apps.get_model("accounts", "UserProfile")

    for broker_profile in BrokerProfile.objects.select_related("user").all():
        user_profile, _ = UserProfile.objects.get_or_create(user_id=broker_profile.user_id)

        if getattr(broker_profile, "rfc", "") and not user_profile.rfc:
            user_profile.rfc = broker_profile.rfc.strip().upper()
        if getattr(broker_profile, "state", "") and not user_profile.state:
            user_profile.state = broker_profile.state.strip()
        if getattr(broker_profile, "city", "") and not user_profile.city:
            user_profile.city = broker_profile.city.strip()
        if broker_profile.identity_verified and user_profile.identity_status == "unverified":
            user_profile.identity_status = "verified"
        user_profile.save()

        broker_profile.operating_state = broker_profile.operating_state or getattr(
            broker_profile,
            "state",
            "",
        )
        broker_profile.primary_market = broker_profile.primary_market or getattr(
            broker_profile,
            "city",
            "",
        )
        broker_profile.license_or_registration_type = (
            broker_profile.license_or_registration_type
            or getattr(broker_profile, "certification_name", "")
        )
        broker_profile.license_or_registration_number = (
            broker_profile.license_or_registration_number
            or getattr(broker_profile, "certification_number", "")
        )
        if broker_profile.company_rfc:
            broker_profile.company_rfc = broker_profile.company_rfc.strip().upper()

        reviewed_at = (
            broker_profile.reviewed_at
            or broker_profile.approved_at
            or broker_profile.rejected_at
            or getattr(broker_profile, "needs_info_at", None)
        )
        broker_profile.reviewed_at = reviewed_at

        is_approved = broker_profile.application_status == "approved"
        broker_profile.can_create_transactions = is_approved
        broker_profile.is_active_broker = is_approved
        broker_profile.professional_info_verified = is_approved
        broker_profile.manual_review_required = not is_approved

        broker_profile.save(
            update_fields=[
                "company_rfc",
                "operating_state",
                "primary_market",
                "license_or_registration_type",
                "license_or_registration_number",
                "reviewed_at",
                "can_create_transactions",
                "is_active_broker",
                "professional_info_verified",
                "manual_review_required",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at_user_updated_at_brokerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerprofile',
            options={'verbose_name': 'Broker profile', 'verbose_name_plural': 'Broker profiles'},
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='can_create_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='is_active_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='license_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='license_or_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='license_or_registration_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='manual_review_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='operating_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='primary_market',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='professional_info_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Mexican phone number in the format +52XXXXXXXXXX.', regex='^\\+52\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='company_rfc',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Mexican RFC.', regex='^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a valid Mexican postal code.', regex='^\\d{5}$')])),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Mexican RFC.', regex='^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$')])),
                ('curp', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='CURP must be a valid Mexican CURP format.', regex='^[A-Z][AEIOUX][A-Z]{2}\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d]\\d$')])),
                ('id_type', models.CharField(blank=True, choices=[('ine', 'INE'), ('passport', 'Passport')], max_length=20)),
                ('id_image', models.FileField(blank=True, null=True, upload_to='accounts/id-images/')),
                ('identity_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.RunPython(
            migrate_broker_data_to_profiles,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='certification_name',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='certification_number',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='needs_info_at',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='state',
        ),
    ]
