# Generated by Django 6.0.4 on 2026-04-17 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_review_workflow_fields(apps, schema_editor):
    BrokerProfile = apps.get_model("accounts", "BrokerProfile")

    BrokerProfile.objects.exclude(application_status="draft").filter(
        review_started_at__isnull=True,
    ).update(review_started_at=models.F("submitted_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_brokerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerprofile',
            options={'permissions': (('review_brokerprofile', 'Can review broker applications'),), 'verbose_name': 'Broker profile', 'verbose_name_plural': 'Broker profiles'},
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='can_create_transactions',
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='applicant_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs info')], default='draft', max_length=20),
        ),
        migrations.RenameField(
            model_name='brokerprofile',
            old_name='review_notes',
            new_name='internal_review_notes',
        ),
        migrations.RunPython(
            backfill_review_workflow_fields,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='identity_verified',
        ),
    ]
