# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations, models


def merge_under_review_into_submitted(apps, schema_editor):
    BrokerProfile = apps.get_model("accounts", "BrokerProfile")
    BrokerProfile.objects.filter(application_status="under_review").update(
        application_status="submitted"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_brokerprofile_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            merge_under_review_into_submitted,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="brokerprofile",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("needs_info", "Needs info"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
