# Generated by Django 6.0.4 on 2026-04-22 03:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_identity_and_broker_records(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    BrokerProfile = apps.get_model("accounts", "BrokerProfile")
    IdentityVerification = apps.get_model("accounts", "IdentityVerification")
    BrokerApplication = apps.get_model("accounts", "BrokerApplication")

    identity_status_map = {
        "unverified": "draft",
        "pending": "submitted",
        "verified": "verified",
        "rejected": "rejected",
    }

    verification_ids_by_user = {}

    for user_profile in UserProfile.objects.all():
        should_create = any(
            [
                user_profile.rfc,
                user_profile.curp,
                user_profile.id_type,
                user_profile.id_image,
                user_profile.identity_status != "unverified",
            ]
        )
        if not should_create:
            continue

        verification = IdentityVerification.objects.create(
            user_id=user_profile.user_id,
            status=identity_status_map.get(user_profile.identity_status, "draft"),
            rfc=(user_profile.rfc or "").strip().upper(),
            curp=(user_profile.curp or "").strip().upper(),
            id_type=user_profile.id_type or "",
            id_image=user_profile.id_image or None,
            manual_review_required=user_profile.identity_status != "verified",
            created_at=user_profile.created_at,
            updated_at=user_profile.updated_at,
        )
        verification_ids_by_user[user_profile.user_id] = verification.pk

    broker_profile_ids_to_delete = []

    for old_profile in BrokerProfile.objects.all():
        verification_id = verification_ids_by_user.get(old_profile.user_id)
        if verification_id is None:
            derived_identity_status = "draft"
            if old_profile.application_status in {"submitted", "needs_info", "rejected"}:
                derived_identity_status = "submitted"
            if old_profile.application_status == "approved":
                derived_identity_status = "verified"

            verification = IdentityVerification.objects.create(
                user_id=old_profile.user_id,
                status=derived_identity_status,
                submitted_at=old_profile.submitted_at,
                review_started_at=old_profile.review_started_at,
                reviewed_at=old_profile.reviewed_at,
                verified_at=old_profile.approved_at if old_profile.application_status == "approved" else None,
                rejected_at=old_profile.rejected_at,
                reviewed_by_id=old_profile.reviewed_by_id,
                applicant_message="",
                internal_review_notes="",
                manual_review_required=derived_identity_status != "verified",
                created_at=old_profile.created_at,
                updated_at=old_profile.updated_at,
            )
            verification_id = verification.pk
            verification_ids_by_user[old_profile.user_id] = verification_id

        application = BrokerApplication.objects.create(
            id=old_profile.pk,
            user_id=old_profile.user_id,
            broker_type=old_profile.broker_type,
            status=old_profile.application_status,
            applicant_message=old_profile.applicant_message,
            internal_review_notes=old_profile.internal_review_notes,
            submitted_at=old_profile.submitted_at,
            review_started_at=old_profile.review_started_at,
            reviewed_at=old_profile.reviewed_at,
            approved_at=old_profile.approved_at,
            rejected_at=old_profile.rejected_at,
            reviewed_by_id=old_profile.reviewed_by_id,
            accepted_broker_declaration_at=old_profile.accepted_broker_declaration_at,
            brokerage_name=old_profile.brokerage_name,
            years_of_experience=old_profile.years_of_experience,
            primary_market=old_profile.primary_market,
            operating_state=old_profile.operating_state,
            license_or_registration_type=old_profile.license_or_registration_type,
            license_or_registration_number=old_profile.license_or_registration_number,
            issuing_authority=old_profile.issuing_authority,
            license_expires_at=old_profile.license_expires_at,
            company_legal_name=old_profile.company_legal_name,
            company_rfc=(old_profile.company_rfc or "").strip().upper(),
            representative_job_title=old_profile.representative_job_title,
            has_authority_to_represent=old_profile.has_authority_to_represent,
            manual_review_required=old_profile.manual_review_required,
            created_at=old_profile.created_at,
            updated_at=old_profile.updated_at,
        )

        if old_profile.application_status == "approved":
            old_profile.approved_application_id = application.pk
            old_profile.identity_verification_id = verification_id
            old_profile.approved_by_id = old_profile.reviewed_by_id
            old_profile.is_active_broker = True
            old_profile.approved_at = old_profile.approved_at or old_profile.reviewed_at
            old_profile.save(
                update_fields=[
                    "approved_application",
                    "identity_verification",
                    "approved_by",
                    "is_active_broker",
                    "approved_at",
                ]
            )
            continue

        broker_profile_ids_to_delete.append(old_profile.pk)

    if broker_profile_ids_to_delete:
        BrokerProfile.objects.filter(pk__in=broker_profile_ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_under_review_into_submitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerprofile',
            options={'verbose_name': 'Broker profile', 'verbose_name_plural': 'Broker profiles'},
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_profiles_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BrokerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker_type', models.CharField(choices=[('individual', 'Individual'), ('company_representative', 'Company representative')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs info')], default='draft', max_length=20)),
                ('applicant_message', models.TextField(blank=True)),
                ('internal_review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_broker_declaration_at', models.DateTimeField(blank=True, null=True)),
                ('brokerage_name', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('primary_market', models.CharField(blank=True, max_length=255)),
                ('operating_state', models.CharField(blank=True, max_length=100)),
                ('license_or_registration_type', models.CharField(blank=True, max_length=255)),
                ('license_or_registration_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('license_expires_at', models.DateField(blank=True, null=True)),
                ('company_legal_name', models.CharField(blank=True, max_length=255)),
                ('company_rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Mexican RFC.', regex='^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$')])),
                ('representative_job_title', models.CharField(blank=True, max_length=255)),
                ('has_authority_to_represent', models.BooleanField(default=False)),
                ('manual_review_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker application',
                'verbose_name_plural': 'Broker applications',
                'db_table': 'broker_applications',
                'ordering': ('-created_at',),
                'permissions': (('review_brokerapplication', 'Can review broker applications'),),
            },
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='approved_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to='accounts.brokerapplication'),
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_info', 'Needs info'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Mexican RFC.', regex='^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$')])),
                ('curp', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='CURP must be a valid Mexican CURP format.', regex='^[A-Z][AEIOUX][A-Z]{2}\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d]\\d$')])),
                ('id_type', models.CharField(blank=True, choices=[('ine', 'INE'), ('passport', 'Passport')], max_length=20)),
                ('id_image', models.FileField(blank=True, null=True, upload_to='accounts/id-images/')),
                ('applicant_message', models.TextField(blank=True)),
                ('internal_review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('manual_review_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity verification',
                'verbose_name_plural': 'Identity verifications',
                'db_table': 'identity_verifications',
                'permissions': (('review_identityverification', 'Can review identity verifications'),),
            },
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='identity_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_profiles', to='accounts.identityverification'),
        ),
        migrations.RunPython(migrate_identity_and_broker_records, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='accepted_broker_declaration_at',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='applicant_message',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='internal_review_notes',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='manual_review_required',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='professional_info_verified',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='review_started_at',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='identity_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rfc',
        ),
    ]
