# Generated by Django 6.0.4 on 2026-04-22 14:51

import django.core.validators
from django.db import migrations, models


def backfill_identity_legal_names(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    IdentityVerification = apps.get_model("accounts", "IdentityVerification")

    users_by_id = {
        user.id: user
        for user in User.objects.all().only("id", "first_name", "middle_name", "last_name")
    }

    for verification in IdentityVerification.objects.all():
        user = users_by_id.get(verification.user_id)
        if user is None:
            continue

        fields_to_update = []

        if not verification.legal_first_name and user.first_name:
            verification.legal_first_name = user.first_name.strip()
            fields_to_update.append("legal_first_name")
        if not verification.legal_middle_name and user.middle_name:
            verification.legal_middle_name = user.middle_name.strip()
            fields_to_update.append("legal_middle_name")
        if not verification.legal_last_name and user.last_name:
            verification.legal_last_name = user.last_name.strip()
            fields_to_update.append("legal_last_name")

        if fields_to_update:
            verification.save(update_fields=fields_to_update)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_brokerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='legal_first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='legal_last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='legal_middle_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.RunPython(backfill_identity_legal_names, migrations.RunPython.noop),
    ]
