# Generated by Django 6.0.4 on 2026-04-22 15:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def merge_identity_verification_into_user_profile(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    IdentityVerification = apps.get_model("accounts", "IdentityVerification")

    profiles_by_user_id = {
        profile.user_id: profile
        for profile in UserProfile.objects.all()
    }

    for verification in IdentityVerification.objects.all():
        profile = profiles_by_user_id.get(verification.user_id)
        if profile is None:
            profile = UserProfile.objects.create(user_id=verification.user_id)
            profiles_by_user_id[verification.user_id] = profile

        profile.status = verification.status
        profile.legal_first_name = verification.legal_first_name
        profile.legal_middle_name = verification.legal_middle_name
        profile.legal_last_name = verification.legal_last_name
        profile.rfc = verification.rfc
        profile.curp = verification.curp
        profile.id_type = verification.id_type
        profile.id_image = verification.id_image
        profile.applicant_message = verification.applicant_message
        profile.internal_review_notes = verification.internal_review_notes
        profile.submitted_at = verification.submitted_at
        profile.review_started_at = verification.review_started_at
        profile.reviewed_at = verification.reviewed_at
        profile.verified_at = verification.verified_at
        profile.rejected_at = verification.rejected_at
        profile.reviewed_by_id = verification.reviewed_by_id
        profile.manual_review_required = verification.manual_review_required
        profile.save(
            update_fields=[
                "status",
                "legal_first_name",
                "legal_middle_name",
                "legal_last_name",
                "rfc",
                "curp",
                "id_type",
                "id_image",
                "applicant_message",
                "internal_review_notes",
                "submitted_at",
                "review_started_at",
                "reviewed_at",
                "verified_at",
                "rejected_at",
                "reviewed_by",
                "manual_review_required",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_identityverification_legal_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerprofile',
            name='identity_verification',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('review_identityverification', 'Can review identity verifications'),), 'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='applicant_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='curp',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='CURP must be a valid Mexican CURP format.', regex='^[A-Z][AEIOUX][A-Z]{2}\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d]\\d$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_image',
            field=models.FileField(blank=True, null=True, upload_to='accounts/id-images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('ine', 'INE'), ('passport', 'Passport')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='internal_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_middle_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='This field contains invalid characters.', regex="^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ'.\\- ]{2,100}$")]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manual_review_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Mexican RFC.', regex='^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_info', 'Needs info'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(merge_identity_verification_into_user_profile, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='IdentityVerification',
        ),
    ]
