# Generated by Django 6.0.4 on 2026-05-04 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('client_content_type', models.CharField(blank=True, max_length=255)),
                ('detected_content_type', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('malware_scan_status', models.CharField(choices=[('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error')], default='SKIPPED', max_length=20)),
                ('malware_scan_detail', models.TextField(blank=True)),
                ('sanitizer', models.CharField(blank=True, max_length=120)),
                ('stored_file_name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_security_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
