# Generated by Django 6.0.4 on 2026-04-26 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_remove_transactionparticipant_uniq_active_single_role_per_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PURCHASE_AGREEMENT', 'Purchase agreement'), ('ESCROW_CONTRACT', 'Escrow contract'), ('GENERIC', 'Generic')], max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_SIGNATURES', 'Awaiting signatures'), ('EXECUTED', 'Executed'), ('VOID', 'Void')], default='DRAFT', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='transactions/documents/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.transaction')),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_transaction_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('earnest_money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('executed_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('inspection_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_scheme_summary', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_agreement', to='documents.transactiondocument')),
            ],
        ),
    ]
