# Generated by Django 6.0.4 on 2026-04-27 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseagreement',
            name='broker_commission_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='buyer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='buyer_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='confirmed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_purchase_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='contingencies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='currency',
            field=models.CharField(default='MXN', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='disbursement_amounts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='disbursement_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='disbursement_payees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='disbursement_purposes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='escrow_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='escrow_bank_account',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='escrow_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='extraction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW_REQUIRED', 'Review required'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='gf_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='payee_wire_information',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='payment_milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='property_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='property_legal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='raw_extraction',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='seller_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='seller_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='special_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseagreement',
            name='wire_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
