# Generated by Django 6.0.4 on 2026-04-23 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Mexico', max_length=120)),
                ('parcel_number', models.CharField(blank=True, max_length=120)),
                ('legal_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('STANDARD', 'Standard'), ('DOUBLE_BROKER', 'Double broker')], default='STANDARD', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_INVITATIONS', 'Pending invitations'), ('PARTIES_CONFIRMED', 'Parties confirmed'), ('KYC_IN_PROGRESS', 'KYC in progress'), ('AWAITING_SIGNATURES', 'Awaiting signatures'), ('AWAITING_DEPOSIT', 'Awaiting deposit'), ('FUNDED', 'Funded'), ('CLOSING_PENDING', 'Closing pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='DRAFT', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('earnest_money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MXN', max_length=10)),
                ('closing_date_target', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.property')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransactionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY_BROKER', 'Primary broker'), ('COOPERATING_BROKER', 'Cooperating broker'), ('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ESCROW_OFFICER', 'Escrow officer')], max_length=40)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('intended_role', models.CharField(choices=[('PRIMARY_BROKER', 'Primary broker'), ('COOPERATING_BROKER', 'Cooperating broker'), ('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ESCROW_OFFICER', 'Escrow officer')], max_length=40)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('LINK', 'Link'), ('QR', 'QR')], default='EMAIL', max_length=20)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transaction_invitations', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transaction_invitations', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='transactions.transaction')),
                ('accepted_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_invitations', to='transactions.transactionparticipant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='transactionparticipant',
            constraint=models.UniqueConstraint(fields=('transaction', 'user'), name='uniq_transaction_user'),
        ),
        migrations.AddConstraint(
            model_name='transactionparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE'), ('role__in', ['BUYER', 'SELLER', 'PRIMARY_BROKER', 'ESCROW_OFFICER'])), fields=('transaction', 'role'), name='uniq_active_single_role_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('target_user__isnull', False), models.Q(('target_email', ''), _negated=True), _connector='OR'), name='invitation_requires_target_user_or_email'),
        ),
    ]
