# Generated by Django 6.0.4 on 2026-04-25 09:24

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def expire_stale_pending_invitations(apps, schema_editor):
    Invitation = apps.get_model("transactions", "Invitation")
    Invitation.objects.filter(
        status="PENDING",
        expires_at__lte=timezone.now(),
    ).update(status="EXPIRED", updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionparticipant',
            name='uniq_active_single_role_per_transaction',
        ),
        migrations.RunPython(expire_stale_pending_invitations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING'), ('target_user__isnull', False)), fields=('transaction', 'target_user'), name='uniq_pending_invitation_per_target_user'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(models.F('transaction'), django.db.models.functions.text.Lower('target_email'), condition=models.Q(('status', 'PENDING'), models.Q(('target_email', ''), _negated=True)), name='uniq_pending_invitation_per_target_email'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING'), ('intended_role__in', ['BUYER', 'SELLER', 'PRIMARY_BROKER', 'COOPERATING_BROKER', 'ESCROW_OFFICER'])), fields=('transaction', 'intended_role'), name='uniq_pending_invitation_per_single_role'),
        ),
        migrations.AddConstraint(
            model_name='transactionparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE'), ('role__in', ['BUYER', 'SELLER', 'PRIMARY_BROKER', 'COOPERATING_BROKER', 'ESCROW_OFFICER'])), fields=('transaction', 'role'), name='uniq_active_single_role_per_transaction'),
        ),
    ]
