# Generated by Django 6.0.4 on 2026-04-28 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transactionparticipant_uniq_active_single_role_per_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCommissionAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSED', 'Proposed'), ('COUNTERED', 'Countered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=30)),
                ('commission_basis', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed amount'), ('PERCENT_OF_PURCHASE_PRICE', 'Percent of purchase price')], max_length=40)),
                ('total_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_commission_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('currency', models.CharField(default='MXN', max_length=10)),
                ('primary_broker_share_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('primary_broker_share_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('cooperating_broker_share_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cooperating_broker_share_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('payment_source', models.CharField(choices=[('SELLER_PROCEEDS', 'Seller proceeds'), ('BUYER_FUNDS', 'Buyer funds'), ('CLOSING_FUNDS', 'Closing funds'), ('OTHER', 'Other')], default='CLOSING_FUNDS', max_length=40)),
                ('payable_event', models.CharField(choices=[('AT_CLOSING', 'At closing'), ('UPON_FUNDING', 'Upon funding'), ('AFTER_CONDITION', 'After condition'), ('OTHER', 'Other')], default='AT_CLOSING', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_commission_agreements', to=settings.AUTH_USER_MODEL)),
                ('proposed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_commission_agreements', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_agreement', to='transactions.transaction')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
